export const refs = {
  main: document.querySelector('main'),
  footerLink: document.querySelector('[data-action="open-modal-teamlist"]'),
  myUlEle: document.querySelectorAll('.nav__title >li a'),
  singinModal: document.querySelector('.backdrop-sing'),
  formReg: document.querySelector('.modal__form-registration'),
  formLog: document.querySelector('.modal__form-login'),
  singUP: document.querySelector('.signup-now__button'),
  singOutMod: document.querySelector('.signup-wpapper '),
  singInMod: document.querySelector('.signin-wpapper '),
  logIn: document.querySelector('.js-login'),
  logOut: document.querySelector('.js-logout'),
  backModal: document.querySelector('.modal__back'),
  idhome: document.querySelector('#home'),
  idmyLib: document.querySelector('#myLib'),
  modalSinInOpen: document.querySelector('.modal-auth--hidden'),
  modalSinInError: document.querySelector('.signin-modal__error'),
  modalSinUpError: document.querySelector('.signup-modal__error'),
  modalSinUP: document.querySelector('.modal-signup '),
};
