export const refs = {
  main: document.querySelector('main'),
  footerLink: document.querySelector('[data-action="open-modal-teamlist"]'),
  myUlEle: document.querySelectorAll('.nav__title >li a'),
  sininModal: document.querySelector('.backdrop-sing'),
  formReg: document.querySelector('.modal__form-registration'),
  formLog: document.querySelector('.modal__form-login'),
  singUP: document.querySelector('.signup-now__button'),
  singInMod: document.querySelector('.backdrop-sing'),
  singOutMod: document.querySelector('.signup-wpapper '),
  singInMod: document.querySelector('.signin-wpapper '),
  logIn: document.querySelector('.js-login'),
  logOut: document.querySelector('.js-logOut'),
  backModal: document.querySelector('.modal__back'),
};
